create table if not exists public.users (
  user_id integer generated by default as identity primary key,
  name varchar(50) not null,
  email varchar(100) not null unique,
  password_hash varchar(255) not null,
  role_id integer not null,
  constraint fk_users_role
    foreign key (role_id)
    references public.role(role_id)
    on update cascade
    on delete restrict
);
