create table if not exists public.address (
  address_id integer generated by default as identity primary key,
  user_id integer not null,
  street varchar(150) not null,
  number varchar(20) not null,
  complement varchar(100),
  neighborhood varchar(100) not null,
  city varchar(100) not null,
  state varchar(50) not null,
  zip_code varchar(20) not null,
  country varchar(50) not null,
  constraint fk_address_user
    foreign key (user_id)
    references public.users(user_id)
    on update cascade
    on delete cascade
);
