create table if not exists public.product (
  product_id integer generated by default as identity primary key,
  name varchar(50) not null,
  price numeric(10, 2) not null,
  stock integer not null,
  img jsonb not null,
  description jsonb not null,
  category_id integer not null,
  constraint fk_product_category
    foreign key (category_id)
    references public.category(category_id)
    on update cascade
    on delete restrict
);
