create table if not exists public.cart (
  cart_id integer generated by default as identity primary key,
  user_id integer not null unique,
  constraint fk_cart_user
    foreign key (user_id)
    references public.users(user_id)
    on update cascade
    on delete cascade
);
