create table if not exists public.cart_item (
  cart_item_id integer generated by default as identity primary key,
  cart_id integer not null,
  product_id integer not null,
  quantity integer not null,
  constraint fk_cart_item_cart
    foreign key (cart_id)
    references public.cart(cart_id)
    on update cascade
    on delete cascade,
  constraint fk_cart_item_product
    foreign key (product_id)
    references public.product(product_id)
    on update cascade
    on delete restrict
);
