create table if not exists public.orders (
  order_id integer generated by default as identity primary key,
  user_id integer not null,
  total_price numeric(10, 2) not null,
  status varchar(50) not null,
  created_at timestamptz not null default now(),
  constraint fk_orders_user
    foreign key (user_id)
    references public.users(user_id)
    on update cascade
    on delete restrict
);
