create table if not exists public.order_item (
  order_item_id integer generated by default as identity primary key,
  order_id integer not null,
  product_id integer not null,
  quantity integer not null,
  unit_price numeric(10, 2) not null,
  constraint fk_order_item_order
    foreign key (order_id)
    references public.orders(order_id)
    on update cascade
    on delete cascade,
  constraint fk_order_item_product
    foreign key (product_id)
    references public.product(product_id)
    on update cascade
    on delete restrict
);
